### ISSUE TITLE
Reconsider naming of the module and repo

### ISSUE THREAD

**Issue by underyx** [kiwicom/peel#2]
It's customary to call a company's API wrapper package… the company's name. https://pypi.python.org/pypi/kiwicom, fortunately, is available, so I'd name the package that.

And the repo name definitely should match the package name, though that won't work once we release wrappers for other languages, so I suggest naming it 'kiwicom-python'.

**Comment by xorwen** [comment]
Agree.
What about `kiwicom.py` instead of `kiwicom-python`?

**Comment by underyx** [comment]
Dots in the repo name are not ideal, since the directory will look like a file at first glance; I'm not even sure if github would allow it. The shortened language name is acceptable.

**Comment by OndraSky** [comment]
Done.
