### ISSUE TITLE
Don't force usage of specific environment variables on users

### ISSUE THREAD

**Issue by underyx** [kiwicom/peel#3]
Not everyone will want to and be able to set exactly these env variables. Even if they were able to, `API_SEARCH` and `API_BOOKING` are pretty bad names; what if google decides they want to use the `API_SEARCH` environment var for their search API, since they have as much right to do that as we do? It will be impossible to use both libraries in the same project.

So, the better way to handle this would be:

1. Just hardcode the default API URLs. There's not much point in requiring people to look for it.
2. Make these parameters of the `Kiwicom` class, so you can override the URL if you need.
3. Optionally you can also make the URLs overridable via environment variable for convenience, but they will have to be called something like `KIWICOM_SEARCH_URL` and `KIWICOM_BOOKING_URL`.

**Comment by blayson** [comment]
Done.
