### ISSUE TITLE
Python 3 compatibility?

### ISSUE THREAD

**Issue by yedpodtrzitko** [kiwicom/peel#9]
Python 2 end of life is nigh, so I am not sure how good idea is to start this package with Python 2 support primarily. How is the compatiblity with Python 3 right now?

**Comment by blayson** [comment]
It works with python 3.

**Comment by yedpodtrzitko** [comment]
Ok, that's good then ^_^
 I'm just asking because I haven't seen any usage of `six` in the code, which usually handles incompatibilities between Py 2 and Py 3. 

Feel free to close this issue then.
